routes/web.php
<?php

use PinSpinner\Category;

Route::get('/', function () {
    return view('welcome');
});

Route::resource('pin', 'PinsController');
Route::resource('board', 'BoardsController');

Route::get('/category', function () {
    $categories = Category::where('user_id', auth()->id())->get();

    return $categories;
});

Route::post('/pin-date/{board}/{pin}', 'PinDatesController@store')->name('pin-date.store');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

@include('layouts.head')

<body class="bg-grey-lighter">
    <div>
        @include('layouts.navbar')

        <div id="app" class="container mx-auto py-12">
            {{--@include('flash::message')--}}

            @yield('content')
        </div>
    </div>

    <script src="{{ mix('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/head.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('/css/main.css') }}" rel="stylesheet">
</head>

resources/views/layouts/navbar.blade.php
<nav class="bg-blue">
    <div class="container mx-auto py-6 flex">

        <h1 class="flex-1"><a href="" class="no-underline text-white hover:text-grey-light">ThePinSpinner</a></h1>

        <div class="flex-1 pt-2">
            <ul class="list-reset flex justify-end text-xl">
                @guest
                    <li class="mr-6">
                        <a class="text-white hover:text-grey-light no-underline" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>

                    <li class="mr-6">
                        <a class="text-white hover:text-grey-light no-underline" href="{{ route('register') }}">{{ __('Register') }}</a>
                    </li>
                @else
                    <li class="mr-6">
                        <a class="text-white hover:text-grey-light no-underline" href="{{ route('board.index') }}">Boards</a>
                    </li>

                    <li class="mr-6">
                        <div>
                            <a class="text-white hover:text-grey-light no-underline" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>

    </div>
</nav>